apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-{{ include "inference.fullname" . }}-dashboard
  namespace: {{ .Values.grafana.namespace }}
  labels:
    {{- toYaml .Values.grafana.dashboard_labels | nindent 4 }}
data:
{{ (.Files.Glob "dashboards/*.json").AsConfig | indent 2 }}
